academy = input("Enter the academy you study in: ")
school = input("Enter the school you study in: ")
name = input("Enter your name: ")
last_name = input("Enter your last name: ")

print("---------------------------------")
print()
print(f"Academy: {academy}")
print()
print("---------------------------------")
print()
print(f"School: {school}")
print()
print("---------------------------------")
print()
print(f"Name: {name}")
print()
print("---------------------------------")
print()
print(f"Last name: {last_name}")
print()
print("---------------------------------")
